name: "Mark Rondina"
description: "Idea Space by Mark Rondina"

url: "http://localhost:4000/blog"
paginate: 10
markdown: rdiscount
permalink: posts/:categories/:year/:month/:day/:title/
pygments: true
auto: true
authors:
  Mark:
    display_name: mrondina
    profile-image: images/mark-profile.jpg
    email: mark@rondina.net
    web: http://www.markrondina.com/
    twitter: mrondina
    github: mrondina