name: "Mark Rondina"
description: "Idea Space by Mark Rondina"

url: "http://markrondina.com"
paginate: 10
markdown: rdiscount
permalink: posts/:categories/:year/:month/:day/:title/
pygments: true
auto: true
authors:
  Mark:
    display_name: Mark Rondina
    profile-image: https://s.gravatar.com/avatar/48f5bbc2752b434e2b6d0ec263da193e?s=200
    email: mark@rondina.net
    web: http://www.markrondina.com/
    twitter: mrondina
    github: mrondina
theme: jekyll-theme-cayman