---
#-------------------------------
# Site Settings
title: Mark Rondina Personal Portfolio
logo: "/images/logo.png" # You can add own logo. For example "/images/logo.svg".
logo_dark: "/images/logo-dark.svg"
description: The professional and personal work of Mark Rondina
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the users can choose the light or dark mode themself.

#-------------------------------
# Author Settings
author_name: Mark ROndina

#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "About"
      url: "/about/"
    #    - title: "Blog"
    #      url: "/blog/"
    - title: "Contact"
      url: "/contact/"
  #   - title: "Pages"
  #     submenu:
  #       - url: "/contact/"
  #         title: "Contact"
  #       - url: "/elements/"
  #         title: "Elements"

#-------------------------------
# Social Settings
social:
  - { icon: "fa-brands fa-linkedin", link: "https://linkedin.com/markrondina" }
  - { icon: "fa-brands fa-instagram", link: "https://instagram.com" }
  - { icon: "fa-brands fa-dribbble", link: "https://dribbble.com" }

# Example of adding a new link to the header and footer - {icon: "fa-brands fa-youtube", link: "https://youtube.com"}
# Other icons can be found at https://fontawesome.com/icons

#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: Mark Rondina <br/><span><i>Product & Design Leader</i></span> # Add the "span" tag to highlight text.
  hero_description: I’m Mark, an experience design and product leader with over 15 years of experience. I seek to build and transform teams to realize customer-centered design that solve real problems.
  hero_image: "/images/knoll-4.png"
  hero_button_contact: Get In Touch
  hero_button_about: About Me

#-------------------------------
# Projects Settings
section_projects_title: Selected Works

#-------------------------------
# Testimonials Section
section_testimonial_title: Recommendations

testimonial_items:
  - name: "Ketaki Rao"
    image: "/images/ketaki-profile.jpeg"
    designation: "Chief Product Officer - data.ai"
    link: "https://www.linkedin.com/in/ketakirao/"
    content: "Within a year of joining, he up-leveled these teams with new processes, improved communications, and a higher bar for excellence. And achieved the highest morale we have ever had in the team through his own brand of purpose-driven leadership. Under his leadership, we evolved data.ai to the best, the #1, in user experience."

  - name: "Wendy Brown"
    image: "/images/wendy-profile.jpeg"
    designation: "Sr Marketing Executive - GE"
    link: "https://www.linkedin.com/in/wendy-brown-210b747/"
    content: "Mark was an excellent leader of the Digital Design and UX team. He is a true visionary who is not afraid to take on a challenge and can be counted on for his creativity and passion to drive continuous improvements or change when necessary. He was also dedicated to redefining the customer experience as well as growing and developing his team."

  - name: "Taylor Dawson"
    image: "/images/taylor-profile.jpeg"
    designation: "Principal Product Manager - Amazon"
    link: "https://www.linkedin.com/in/j-taylor-dawson/"
    content: "Mark is first and foremost an excellent UX director. With several high-impact projects under his belt (ranging from consumer-facing corporate websites to fast growing native mobile apps...just look at his profile), Mark has a broad range of experience to draw upon."

#-------------------------------
# Blog Section
section_blog_title: Read Latest Posts
#-------------------------------

# Tags Section
section_tags_title: Explore Topics

#-------------------------------
# Newsletter Settings
mailchimp_settings:
  enable: false
  mailchimp_title: Get interesting news
  mailchimp_identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
  mailchimp_input_text: Enter your email address
  mailchimp_background_image: /images/subscribe-bg.jpg

#-------------------------------
# Footer Settings
footer_description: I’m Mark, a transformative product & design leader. I'm passionate about working collaboratively to build intuitively design, customer-centric products that deliver real business impact.

#-------------------------------
# Footer Navigation Settings
footer_menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "About"
      url: "/about/"
    #  - title: "Projects"
    #   url: "/projects/"
    - url: "/blog/"
      title: "Blog"
    - url: "/contact/"
      title: "Contact"
  #   - url: "/elements/"
  #     title: "Elements"

#-------------------------------
# Contact Settings
contact:
  email: mark@rondina.net # Add your form_id
  description: Get in touch. # Add a description of your form

# NOTE
# Simpler theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.

#-------------------------------
# Comment Section (Disqus)
#disqus_identifier: anvodstudio-demo # Add your shortname for Disqus Comment. For example anvodstudio-demo

#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id
